project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

execute:
  freeze: auto
  
website:
  title: "Siddharth Vishwanath"
  favicon: icons/icon-48x48.png
  twitter-card: true
  open-graph: true
  google-analytics: "UA-41844991-1"
  description: "Homepage"
  page-footer:
    left: '`Siddharth Vishwanath. 2023`'
    right: "`Built with` [`Quarto`](https://quarto.org/)"
  navbar:
    align: center
    logo: icons/icon-192x192.png
    title: false
    pinned: true
    search: true
    style: fixed
    background: light
    collapse-level: 1
    # right:
    #   - icon: github
    #     href: https://github.com/
    #   - icon: twitter
    #     href: https://twitter.com
    # left:
    right:
    - href: /
      text: Home
    - href: research.qmd
      text: Research
    - href: teaching.qmd
      text: Teaching
    - href: talks.qmd
      text: Talks
    - href: src/cv.qmd
      text: CV
    - href: 404.qmd
      text: $\zeta(-1)$
format:
  html:
    theme: 
      light: cosmo
      # dark: slate
    css: 
      - theme/css/colors.css
      - theme/css/custom.css
      - theme/css/styles.css
      # - theme/css/theme.scss
    toc: true
    html-math-method: katex
    include-in-header:
      file: theme/html/header.html
    include-after-body: 
      file: theme/html/footer.html