---
title: "CV"
permalink: /cv/
redirect_from:
  - /cv
execute:
  freeze: true
---


My CV is available as a [PDF here](/files/cv.pdf). (Updated Dec 2022)


:::: {.grid}


::: {.g-col-12 .g-col-md-6 style="text-align: left;"}
## Education

{{< fa graduation-cap >}} &nbsp; [**Penn State University**]{} <br> _Ph.D. Candidate, Statistics_,   2017---Present

{{< fa graduation-cap >}} &nbsp; [**Indian Institute of Technology, Kanpur**]{} <br> _M.Sc. (Integrated), Mathematics_,   2015


## Awards

{{< fa star >}} &nbsp; **Student Travel Award** <br> _Geometric Data Analysis, University of Chicago_, 2019

{{< fa star >}} &nbsp; **Proficiency Medal** <br> _Indian Institute of Technology - Kanpur_, 2015

{{< fa star >}} &nbsp; **Academic Excellence Award** <br> _Indian Institute of Technology - Kanpur_, 2015

{{< fa star >}} &nbsp; **KVPY Fellowship** <br> _Department of Science & Technology_ <br> _Government of India_, 2010---2015
:::

::: {.g-col-12 .g-col-md-6 style="text-align: left;"}

## Professional Experience

{{< fa briefcase >}} &nbsp; **IBM Research** <br> _Research Intern_,   2022

{{< fa briefcase >}} &nbsp;  **Penn State University** <br> _Statistical Consultant_,   2019---2022

{{< fa briefcase >}} &nbsp; **Institute of Statistical Mathematics** <br> _Visiting Student Researcher_,  2019 & 2018

{{< fa briefcase >}} &nbsp; **Goldman Sachs** <br> _Senior Quantitative Analyst_,   2016---2017

{{< fa briefcase >}} &nbsp; **Nomura** <br>  _Model Validation Quant_,   2015---2016

:::




::::

<!-- 
---

#### Academic experience

{{< fa feather >}} &nbsp;  Graduate Research Assistant, Penn State University, July 2020 <br> [*Hamiltonian Monte Carlo for Multimodal Sampling.* Supervised by Hyungsuk Tak]{.small}

{{< fa feather >}} &nbsp;  Graduate Research Assistant, Penn State University, June 2020 <br> [*Robust persistence diagrams using reproducing kernels.* Supervised by Bharath Sriperumbudur]{.small}

{{< fa feather >}} &nbsp;  Visiting researcher, Institute of Statistical Mathematics - Tokyo, 2019 <br> [*Robust persistence diagrams.* Hosted by Satoshi Kuriki & Kenji Fukumizu]{.small}

{{< fa feather >}} &nbsp;  Visiting researcher, Institute of Statistical Mathematics - Tokyo, 2018 <br> [*Statistical inference from Betti numbers.* Hosted by Satoshi Kuriki & Kenji Fukumizu]{.small}


---

#### Skills

{{< fa terminal >}} Programming &nbsp; `Julia, R, Python, C/C++, MATLAB, SQL`

{{< fa earth-americas >}} Languages &nbsp; `English, Kannada, Hindi, French`

---

#### Leadership and Service

{{< fa hand-holding-heart >}} &nbsp; **Finance Convener**, Students' Senate, Indian Institute of Technology Kanpur

{{< fa hand-holding-heart >}} &nbsp; **Undergraduate Senator**, Indian Institute of Technology Kanpur -->